spring:
  data:
    mongodb:
      port: 27017
      host: 127.0.0.1
      database: filesys
  mvc:
    view:
      prefix: /
      suffix: .html
  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 102400MB
      max-request-size: 102400MB


server:
  port: 8088
  context-path: /SharedFS
  jsp-servlet:
    init-parameters:
      development: true





